---
title: "Compare PCSS and RAVs"
author: "Sehyun Oh"
date: "`r Sys.Date()`"
output:
  BiocStyle::html_document:
    toc: true
    toc_float: false
    toc_depth: 3
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, collapse = TRUE)
```

```{r echo=FALSE, message=FALSE, warning=FALSE}
## Packages in GitHub
pkgs <- c("PCAGenomicSignatures")
new_pkgs <- pkgs[!(pkgs %in% rownames(installed.packages()))]
if(length(new_pkgs) != 0) devtools::install_github(paste0("shbrief/", new_pkgs))

## Load packages
suppressPackageStartupMessages({
  library(PCAGenomicSignatures)
})
```

# avgLoading from CRC paper
```{r}
avgLoading <- read.table("data/avg_loadings.csv", 
                         header = TRUE, sep = ",")
avgLoading <- tibble::column_to_rownames(avgLoading, var="X")
colnames(avgLoading) <- paste0("PCSS", 1:4)
```

# PCAmodel
```{r message=FALSE, warning=FALSE, collapse=FALSE}
data.dir <- system.file("extdata", package = "PCAGenomicSignaturesPaper")
PCAmodel <- readRDS(file.path(data.dir, "PCAmodel_C2.rds"))
PCAmodel
updateNote(PCAmodel)
```

# PCclusters most similar to PCSS1/PCSS2
```{r}
cg <- intersect(rownames(avgLoading), rownames(PCAmodel))
loading_cor <- abs(stats::cor(avgLoading[cg,], model(PCAmodel)[cg,], 
                              use = "pairwise.complete.obs", method = "pearson"))

max1 <- which.max(loading_cor[1,])  # max. correlation with PCSS1
max2 <- which.max(loading_cor[2,])  # max. correlation with PCSS2

loading_cor[1, max1, drop = FALSE]
loading_cor[2, max2, drop = FALSE]
```

```{r}
annotatePCcluster(PCAmodel, 1575)
annotatePCcluster(PCAmodel, 834)
```

```{r}
sessionInfo()
```

