---
title: "bcellViper data analysis"
author: "Sehyun Oh"
date: "`r Sys.Date()`"
output:
  BiocStyle::html_document:
    toc: true
    toc_float: false
    toc_depth: 3
vignette: >
  %\VignetteIndexEntry{Evaluate validation score and silhouette width for interpretation}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
abstract: "[**Source Code**]()"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, collapse = TRUE, message = FALSE, 
                      out.height = "70%", out.width = "70%")
```

```{r}
suppressPackageStartupMessages({
  library(GenomicSuperSignature)
  library(dplyr)
  library(bcellViper)
})
```

```{r}
dir <- "~/GSS/GenomicSuperSignatureLibrary/refinebioRseq/RAVmodel_536"
RAVmodel <- readRDS(file.path(dir, "refinebioRseq_RAVmodel_C2CP_20220119.rds"))
RAVmodel

version(RAVmodel)
```


```{r}
data(bcellViper)
val_all <- validate(dset, RAVmodel)
```

```{r fig.width=4, fig.height=2.5, out.height = "50%", out.width = "50%"}
res <- validatedSignatures(val_all, RAVmodel, swCutoff = 0)
res

val_ind <- res[,"cl_num"] 
heatmapTable(val_all, RAVmodel, swCutoff = 0)
```

```{r}
res_all <- vector(mode = "list", length = 5)
for (i in seq_along(val_ind)) {
    res <- subsetEnrichedPathways(RAVmodel, val_ind[i], n = 10, both = TRUE, 
                                  include_nes = TRUE) %>% as.data.frame
    res_all[[i]] <- res
}

res_all <- Reduce(cbind, res_all)
write.csv(res_all, "bcellViper_gsea_c2.csv")
```

```{r fig.width=9, fig.height=9}
for (i in val_ind) {
    drawWordcloud(RAVmodel, i)
}
```

