---
title: "Reproduce multiPLIER Figure 3"
author: "Sehyun Oh"
date: "`r format(Sys.time(), '%B %d, %Y')`"
vignette: >
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteIndexEntry{Quickstart}
  %\VignetteEncoding{UTF-8}
output:
  BiocStyle::html_document:
    number_sections: no
    toc: yes
    toc_depth: 3
  BiocStyle::pdf_document:
    toc: true
    toc_float: false
    toc_depth: 3
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  comment = "#>", collapse = TRUE, message = FALSE, warning = FALSE, eval=FALSE
)
```

```{r, echo=FALSE, results="hide", warning=FALSE, eval=FALSE}
if (!"pathwork" %in% installed.packages())
    devtools::install_github("thomasp85/patchwork")
```

```{r}
suppressPackageStartupMessages({
  library(patchwork)
  library(pdftools)
})
```

```{r}
plot1 <- readRDS("SLE-WB/outputs/neutrophil_count.rds")
plot2 <- readRDS("SLE-WB/outputs/neutrophil_estimate.rds")
plot3 <- readRDS("NARES/outputs/nares_neutrophil.rds")
```

```{r fig.width=11, fig.height=4.3, eval=FALSE}
plot_all <- plot1 | plot2 | plot3
plot_all
```

```{r fig_4, fig.width=11, fig.height=3.8}
plot_all <- ggpubr::ggarrange(plot1, plot2, plot3, 
                              labels = c("A", "B", "C"), 
                              font.label = list(size = 20),
                              ncol = 3)
plot_all
```

```{r echo=FALSE, eval=FALSE}
png("multiPLIER_Fig3.png", width = 1100, height = 380)
plot_all
dev.off()
```

# Session Info
```{r}
sessionInfo()
```
